[2024-06-19T14:42:43.485+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: shopify_user.streaming_task manual__2024-06-19T14:41:53.913383+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
