[2024-06-22T02:33:07.042+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T02:33:07.060+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shopify_user.streaming_task manual__2024-06-22T02:32:59.339920+00:00 [queued]>
[2024-06-22T02:33:07.071+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shopify_user.streaming_task manual__2024-06-22T02:32:59.339920+00:00 [queued]>
[2024-06-22T02:33:07.072+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-22T02:33:07.099+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): streaming_task> on 2024-06-22 02:32:59.339920+00:00
[2024-06-22T02:33:07.111+0000] {standard_task_runner.py:63} INFO - Started process 40295 to run task
[2024-06-22T02:33:07.115+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'shopify_user', 'streaming_task', 'manual__2024-06-22T02:32:59.339920+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streams_shopify.py', '--cfg-path', '/tmp/tmprzw3pau9']
[2024-06-22T02:33:07.127+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask streaming_task
[2024-06-22T02:33:07.154+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-22T02:33:07.221+0000] {task_command.py:426} INFO - Running <TaskInstance: shopify_user.streaming_task manual__2024-06-22T02:32:59.339920+00:00 [running]> on host 80038ba0413b
[2024-06-22T02:33:07.339+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gauss' AIRFLOW_CTX_DAG_ID='shopify_user' AIRFLOW_CTX_TASK_ID='streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T02:32:59.339920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T02:32:59.339920+00:00'
[2024-06-22T02:33:07.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T02:33:07.372+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:33:07.373+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-06-22T02:33:07.374+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Connection complete.
[2024-06-22T02:33:07.490+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-06-22T02:33:07.490+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-06-22T02:33:07.501+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:33:07.502+0000] {conn.py:410} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Connection complete.
[2024-06-22T02:33:07.503+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka1:29092 <connected> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. 
[2024-06-22T02:33:15.254+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connected> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
[2024-06-22T02:33:15.531+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:33:17.696+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:33:17.703+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]> returned error 111. Disconnecting.
[2024-06-22T02:33:17.712+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-22T02:33:17.721+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:33:17.725+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:33:17.726+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]> returned error 111. Disconnecting.
[2024-06-22T02:33:17.728+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-22T02:33:17.729+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:33:17.781+0000] {conn.py:380} INFO - <BrokerConnection node_id=2 host=kafka2:29093 <connecting> [IPv4 ('172.30.0.6', 29093)]>: connecting to kafka2:29093 [('172.30.0.6', 29093) IPv4]
[2024-06-22T02:33:17.782+0000] {conn.py:410} INFO - <BrokerConnection node_id=2 host=kafka2:29093 <connecting> [IPv4 ('172.30.0.6', 29093)]>: Connection complete.
[2024-06-22T02:33:17.942+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:33:17.946+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]> returned error 111. Disconnecting.
[2024-06-22T02:33:17.947+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-22T02:33:17.948+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:33:19.083+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:33:19.085+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]> returned error 111. Disconnecting.
[2024-06-22T02:33:19.087+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-22T02:33:19.095+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:33:19.868+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:33:19.869+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]> returned error 111. Disconnecting.
[2024-06-22T02:33:19.870+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-22T02:33:19.870+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:33:20.803+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:33:20.804+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]> returned error 111. Disconnecting.
[2024-06-22T02:33:20.805+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-22T02:33:20.805+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:33:29.651+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka1:29092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-06-22T02:33:29.652+0000] {conn.py:315} ERROR - DNS lookup failed for kafka1:29092 (0)
[2024-06-22T02:33:37.656+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka1:29092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-06-22T02:33:37.658+0000] {conn.py:315} ERROR - DNS lookup failed for kafka1:29092 (0)
[2024-06-22T02:33:45.662+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka1:29092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-06-22T02:33:45.663+0000] {conn.py:315} ERROR - DNS lookup failed for kafka1:29092 (0)
[2024-06-22T02:33:45.666+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('shopify.items1', 0) with base offset -1 log start offset None and error None.
[2024-06-22T02:33:45.667+0000] {record_accumulator.py:332} WARNING - Expired 1 batches in accumulator
[2024-06-22T02:33:53.670+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka1:29092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-06-22T02:33:53.673+0000] {conn.py:315} ERROR - DNS lookup failed for kafka1:29092 (0)
[2024-06-22T02:34:01.675+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka1:29092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-06-22T02:34:01.676+0000] {conn.py:315} ERROR - DNS lookup failed for kafka1:29092 (0)
[2024-06-22T02:34:09.679+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka1:29092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-06-22T02:34:09.680+0000] {conn.py:315} ERROR - DNS lookup failed for kafka1:29092 (0)
[2024-06-22T02:34:13.683+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:34:13.685+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]> returned error 111. Disconnecting.
[2024-06-22T02:34:13.685+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-22T02:34:13.686+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:34:13.687+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: connecting to kafka1:29092 [('172.30.0.9', 29092) IPv4]
[2024-06-22T02:34:13.688+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]> returned error 111. Disconnecting.
[2024-06-22T02:34:13.688+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka1:29092 <connecting> [IPv4 ('172.30.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-22T02:34:13.689+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2024-06-22T02:34:17.281+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('shopify.items1', 0) with base offset -1 log start offset None and error None.
[2024-06-22T02:34:17.282+0000] {record_accumulator.py:332} WARNING - Expired 1 batches in accumulator
[2024-06-22T02:34:17.285+0000] {conn.py:919} INFO - <BrokerConnection node_id=2 host=kafka2:29093 <connected> [IPv4 ('172.30.0.6', 29093)]>: Closing connection. 
[2024-06-22T02:34:17.288+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-22T02:34:17.290+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T02:34:17.343+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=shopify_user, task_id=streaming_task, run_id=manual__2024-06-22T02:32:59.339920+00:00, execution_date=20240622T023259, start_date=20240622T023307, end_date=20240622T023417
[2024-06-22T02:34:17.394+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-22T02:34:17.432+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-22T02:34:17.438+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
